size(950, 980);
text("Waarom is Jezus gestorven?", 30, 100);
text("Het antwoord uit de Bijbel", 30, 120);
text("Jezus is gestorven zodat mensen vergeving van zonden en eeuwig leven kunnen krijgen", 30, 140);
text("Met Jezus’ dood werd ook bewezen dat een mens trouw aan God kan blijven, zelfs onder de ergste beproevingen.", 30, 160);
text("Hoe kon de dood van één man zo veel tot stand brengen?", 30, 180);
text("Jezus is gestorven voor ‘de vergeving van onze zonden’", 30, 220);
text("De eerste mens Adam was volmaakt, of zonder zonde, toen hij gemaakt werd.", 30, 240);
text("Maar hij koos ervoor God ongehoorzaam te zijn.", 30, 260);
text("Zijn ongehoorzaamheid of zonde had grote gevolgen voor al zijn nakomelingen.", 30, 280);
text("In de Bijbel staat: ‘Door de ongehoorzaamheid van de ene mens werden velen tot zondaars gesteld’", 30, 300);
text("Ook Jezus was volmaakt, maar hij heeft nooit gezondigd.", 30, 340);
text("Daarom kon hij ‘een verzoening voor onze zonden zijn’.", 30, 360);
text("Door Adams ongehoorzaamheid werden alle mensen zondaars,", 30, 380);
text("maar door Jezus’ dood konden alle mensen die in hem geloven, vergeving krijgen van hun zonden.", 30, 400);
text("Voor meer informatie ga naar: https://jw.org/nl/wat-de-bijbel-leert/vragen/waarom-is-jezus-gestorven/", 30, 440);
